name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * *   # 8 AM IST EVERYDAY
    - cron : 00 14 * * *   # 7.30 PM EVERYDAY

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        
      - name: Install Nodejs and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install newman and Html - extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run postman collection with newman
        run: |
             newman run Inwarranty-flow-collection.postman_collection.json \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra
             

      - name: neman report 
        if: always()   #ensure that archive executed irrespective whether previous step passed or not!
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html
      
















             
      
      
